services:
  web:
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - APP_TITLE=${APP_TITLE}
      - LOG_LEVEL=${LOG_LEVEL}
    deploy:
      replicas: 2
    profiles:
      - staging
  nginx-dev:
    ports:
      - "8081:80"
    profiles:
      - staging
  redis:
    profiles:
      - staging
