services:
  web-prod:
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - APP_TITLE=${APP_TITLE}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Add this
    deploy:
      replicas: 3
  nginx-prod:
    ports:
      - "8082:80"
