apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
    component: redis-backend
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP    
