name: CI for Flask + Redis App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Compose services
        run: |
          echo "REDIS_PASSWORD=supersecretpassword" > .env
          echo "REDIS_HOST=redis-service" >> .env
          echo "APP_TITLE=CI Test App" >> .env
          echo "APP_TITLE_PROD=CI Test Prod App" >> .env
          docker compose --profile dev build
          docker compose --profile test build
      - name: Run unit tests
        run: docker compose --profile test up --build --exit-code-from test
      - name: Run Docker Compose services
        run: docker compose --profile dev up -d --wait
      - name: Test application
        run: |
          curl --retry 3 --retry-delay 5 http://localhost:8080 | grep "CI Test App"
          curl --retry 3 --retry-delay 5 http://localhost:8080/health | grep "OK"
      - name: Clean up
        run: docker compose down
